"""Populate observability contextvars for the request lifetime.

Reads ``X-Request-Id`` from the inbound request (or mints a UUID4 when
absent), binds it to ``request_id_var`` for the request lifetime, and
echoes it back on the response so a caller can correlate client-side
logs with our server-side logs.

``user_id_var`` is bound in the auth dependency rather than here: the
binding has to land next to the GUC bracket that sets
``SET LOCAL app.user_id`` so the value RLS sees and the value the log
emits never diverge. The middleware only owns request-id.

Implemented as pure ASGI middleware (not ``BaseHTTPMiddleware``)
because ``BaseHTTPMiddleware`` runs the inner app in a sub-task and
re-raises exceptions through its ``call_next`` channel — which breaks
FastAPI exception handlers and causes 500 responses to escape past the
``CORSMiddleware`` wrapper (the response gets generated by Starlette's
outer ``ServerErrorMiddleware`` without CORS headers). The 2026-06-07
demo-day overview 500 was misdiagnosed as a CORS bug because of this
trap; ``tests/test_cors.py`` pins the regression.
"""

from __future__ import annotations

import uuid
from typing import TYPE_CHECKING

from horizons_core.observability.logging import request_id_var

if TYPE_CHECKING:
    from starlette.types import ASGIApp, Message, Receive, Scope, Send


class RequestContextMiddleware:
    """Bind ``request_id_var`` for the duration of each HTTP request."""

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        request_id = self._extract_or_mint_request_id(scope)
        token = request_id_var.set(request_id)

        async def send_with_request_id(message: Message) -> None:
            if message["type"] == "http.response.start":
                headers = list(message.get("headers") or [])
                # Replace any inbound x-request-id header to keep the
                # echoed value canonical (the response builder may have
                # set its own).
                headers = [(k, v) for (k, v) in headers if k.lower() != b"x-request-id"]
                headers.append((b"x-request-id", request_id.encode("latin-1")))
                message = {**message, "headers": headers}
            await send(message)

        try:
            await self.app(scope, receive, send_with_request_id)
        finally:
            request_id_var.reset(token)

    @staticmethod
    def _extract_or_mint_request_id(scope: Scope) -> str:
        raw_headers: list[tuple[bytes, bytes]] = scope.get("headers") or []
        for key, value in raw_headers:
            if key.lower() == b"x-request-id":
                try:
                    return value.decode("latin-1")
                except UnicodeDecodeError:
                    break
        return uuid.uuid4().hex
